version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    depends_on:
      - postgres
    volumes:
      - ./examples:/app/examples
      - ./output:/app/output
